version: 2.1

orbs:
  php: circleci/php@1.1.0
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  test-and-deploy:
    jobs:
      # PHP Orb
      - php/test:
          name: Test
          version: '8.0'
      - php/test:
          name: Lint
          test-command: lint
          version: '8.0'
      - aws-ecr/build-and-push-image:
          context: aws-ce
          repo: tadashi-demo-php-apprunner
